[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = [
  '@openzeppelin/=lib/openzeppelin-contracts/',
  'forge-std/=lib/forge-std/src/'
]
solc_version = '0.8.26'
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./" }]
evm_version = 'cancun'

[fmt]
line_length = 100
tab_width = 2
